# Generated by Django 5.1.5 on 2025-01-24 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_contact_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='user',
        ),
    ]
