# Generated by Django 5.1.5 on 2025-01-21 03:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_customuser_address_customuser_age_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaundryBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('note', models.TextField(blank=True)),
                ('weight_kg', models.PositiveIntegerField()),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed')], default='pending', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Laundry Booking',
                'verbose_name_plural': 'Laundry Bookings',
            },
        ),
    ]
